/**
 * Agent mascots: the little companions that walk behind a player.
 *
 * A player says how many they have and *what they look like* (for now by hand,
 * on the entry screen; later the count will be however many agents Chiron
 * reports for them) and both travel with their identity, are validated by the
 * server and end up in the synced state, so **everyone** sees everyone else's
 * mascots as their owner chose them.
 *
 * Count and type are the only inputs: nothing downstream cares where they came
 * from, and the type is one per person — all of somebody's mascots look alike.
 */

/** Nobody has mascots unless they ask for them. */
export const DEFAULT_AGENTS = 0

/** How many mascots one player may have at once. */
export const MAX_AGENTS = 10

/**
 * Normalises an agent count from an untrusted source (the join options): it
 * is an integer in `[0, MAX_AGENTS]` or it becomes one. Anything that is not
 * a finite number at all — a string, `undefined`, `NaN` — reads as "none",
 * and a fractional count is truncated (2.5 robots is 2 robots).
 */
export function sanitizeAgentCount(value: unknown): number {
  if (typeof value !== 'number' || !Number.isFinite(value)) return DEFAULT_AGENTS
  return Math.min(MAX_AGENTS, Math.max(0, Math.floor(value)))
}

/**
 * Sprite sheets of the mascots: small figures, deliberately smaller than the
 * avatars' 32x48 frame, so one next to a person reads as a companion and not
 * as another player. Every type shares this one frame size, whatever it is
 * that it draws inside it.
 *
 * A sheet follows the same frame layout as the avatars (see `ANIM_START` in
 * `avatars.ts`) minus the seated poses, which a mascot has no use for:
 *
 *   idle: right 0-5 - up 6-11 - left 12-17 - down 18-23
 *   walk: right 24-29 - up 30-35 - left 36-41 - down 42-47
 *
 * They are generated by `tools/make-mascot.py`.
 */
export const MASCOT_FRAME = { width: 16, height: 24, count: 48 } as const

/**
 * A kind of mascot: an id — which names its sheet,
 * `apps/client/public/assets/mascots/<id>.png` — and the name the picker
 * shows.
 */
export interface AgentTypeInfo {
  id: string
  /** Name shown in the entry screen's picker. */
  label: string
}

/**
 * The catalogue of looks a person can give their agents. It is fixed and
 * shared: the entry screen builds the picker from it, the server validates
 * against it and every client loads one sheet per entry, so adding a mascot
 * costs one line here plus its PNG.
 *
 * `robot` comes first because it is the default, and it is the sheet that was
 * already in the office: an identity from before there was a choice keeps
 * exactly the mascots it had.
 */
export const AGENT_TYPES: readonly AgentTypeInfo[] = [
  { id: 'robot', label: 'Robot' },
  { id: 'classic', label: 'Classic bot' },
  { id: 'duck', label: 'Duck' },
  { id: 'cat', label: 'Cat' },
]

export const AGENT_TYPE_IDS: readonly string[] = AGENT_TYPES.map((t) => t.id)

/** What someone's mascots look like unless they say otherwise. */
export const DEFAULT_AGENT_TYPE = AGENT_TYPES[0].id

export function isAgentTypeId(value: unknown): value is string {
  return typeof value === 'string' && AGENT_TYPE_IDS.includes(value)
}

/**
 * Normalises a mascot type from an untrusted source (the join options, or an
 * identity stored by an older version of the client): it is an id from the
 * catalogue or it becomes the default. An unknown id, an empty string, a
 * number, `undefined` — they all read as "the usual robot", because a mascot
 * that cannot be drawn is worse than one nobody chose.
 */
export function sanitizeAgentType(value: unknown): string {
  return isAgentTypeId(value) ? value : DEFAULT_AGENT_TYPE
}
