/**
 * Agent mascots: the little robots that walk behind a player.
 *
 * A player says how many they have (for now by hand, on the entry screen;
 * later it will be however many agents Chiron reports for them) and that
 * number travels with their identity, is validated by the server and ends up
 * in the synced state, so **everyone** sees everyone else's robots.
 *
 * The count is the only input: nothing downstream cares where it came from.
 */

/** Nobody has mascots unless they ask for them. */
export const DEFAULT_AGENTS = 0

/** How many mascots one player may have at once. */
export const MAX_AGENTS = 10

/**
 * Normalises an agent count from an untrusted source (the join options): it
 * is an integer in `[0, MAX_AGENTS]` or it becomes one. Anything that is not
 * a finite number at all — a string, `undefined`, `NaN` — reads as "none",
 * and a fractional count is truncated (2.5 robots is 2 robots).
 */
export function sanitizeAgentCount(value: unknown): number {
  if (typeof value !== 'number' || !Number.isFinite(value)) return DEFAULT_AGENTS
  return Math.min(MAX_AGENTS, Math.max(0, Math.floor(value)))
}

/**
 * Sprite sheet of the robot mascot: deliberately smaller than the avatars'
 * 32x48 frame, so a robot next to a person reads as a companion and not as
 * another player.
 *
 * The sheet follows the same frame layout as the avatars (see `ANIM_START` in
 * `avatars.ts`) minus the seated poses, which a robot has no use for:
 *
 *   idle: right 0-5 - up 6-11 - left 12-17 - down 18-23
 *   walk: right 24-29 - up 30-35 - left 36-41 - down 42-47
 *
 * It is generated by `tools/make-mascot.py`.
 */
export const MASCOT_FRAME = { width: 16, height: 24, count: 48 } as const
