#!/usr/bin/env python3
"""
Splits each base avatar (adam, ash, lucy, nancy) into the aligned layers a
composed avatar is drawn with -- body, hair, top, pants, shoes -- and generates
the skin-tone variants of the body layer.  Every layer but the body is saved in
greyscale so it can be tinted at runtime with Phaser's `setTint()`.

Development only: the result is committed in
apps/client/public/assets/avatars/layers/.  Requires Python 3 and Pillow.

Usage:  python3 tools/split-layers.py
        python3 tools/gen-hair.py          # the other four hair styles
        python3 tools/gen-facial-hair.py   # beards, on top of what this writes

Layout of each layer: 1664x48 px (52 frames of 32x48), the same LimeZu layout as
the full avatars.  The pixels that do not belong to the layer are left
transparent (alpha 0).  The art inside those frames is drawn on a 2x grid (16x24
drawn pixels per frame), which is why everything here works in steps of two.

Layers:
  body        -- skin, face, outlines; EVERYTHING but the parts below.
  hair-short  -- the cropped cut the character is drawn with, greyscale.
  top         -- torso clothing only, greyscale.
  pants       -- the legs, greyscale.
  shoes       -- the feet, greyscale.

The skin variants are generated by remapping the skin colours (a subset of
PROTECTED) with an HSV rotation, in the style of person-avatars.py.  The
outlines and the mouth do not change.

LimeZu's licence allows editing the assets (see docs/asset-licenses.md).
"""
from __future__ import annotations

import colorsys
from pathlib import Path

from PIL import Image

AVATARS_DIR = Path(__file__).resolve().parents[1] / "apps/client/public/assets/avatars"
LAYERS_DIR = AVATARS_DIR / "layers"

FRAME_W, FRAME_H = 32, 48  # one frame of the sprite sheet
ART = 2  # the sheets are 2x art: every drawn pixel is a 2x2 block

# Bounds for the hem the silhouette suggests; the legs never start outside them.
HEM_MIN, HEM_MAX, HEM_DEFAULT = 36, 40, 40

# ---------------------------------------------------------------------------
# Colours shared by the 4 base characters.  They are the PROTECTED set of
# recolor-avatars.py: skin, mouth, outlines and shadows.
# ---------------------------------------------------------------------------
PROTECTED = {
    (58, 58, 80),
    (70, 70, 94),
    (86, 89, 114),
    (108, 89, 129),
    (120, 125, 147),
    (171, 74, 54),
    (199, 140, 89),
    (211, 163, 141),
    (246, 174, 159),
    (255, 203, 176),
}

# Shades of bare skin that are not in PROTECTED: the forearms and hands, which
# hang level with the hip and must not be painted in the trouser colour.
BARE_SKIN = {(255, 184, 147), (246, 151, 132)}

# The subset of PROTECTED that is skin (remapped for the skin tones).
SKIN_COLORS = {
    (199, 140, 89),
    (211, 163, 141),
    (246, 174, 159),
    (255, 203, 176),
}

# ---------------------------------------------------------------------------
# HAIR colours per base sprite (from person-avatars.py + adam, analysed).
# ---------------------------------------------------------------------------
HAIR: dict[str, set[tuple[int, int, int]]] = {
    # adam's hair is the olive mop, not the purple shirt: the two sets used to
    # be the other way round, which tinted his shirt with the hair colour.
    "adam": {(104, 114, 83), (93, 96, 67), (95, 105, 74), (149, 157, 88)},
    "ash": {(141, 112, 81), (138, 101, 82), (149, 115, 80), (186, 141, 94), (111, 84, 70)},
    "lucy": {
        (171, 103, 54),
        (179, 123, 63),
        (204, 150, 89),
        (175, 114, 59),
        (194, 136, 75),
        (179, 94, 63),
        (119, 73, 52),
    },
    "nancy": {
        (114, 74, 64),
        (128, 84, 73),
        (131, 91, 76),
        (134, 97, 80),
        (123, 81, 71),
        (100, 73, 66),
    },
}

# ---------------------------------------------------------------------------
# CLOTHING colours (torso) per base sprite.
# ---------------------------------------------------------------------------
TOP: dict[str, set[tuple[int, int, int]]] = {
    "adam": {(128, 94, 142), (159, 116, 168)},
    "ash": {
        (90, 68, 74),
        (111, 73, 77),
        (162, 57, 75),
        (174, 74, 82),
        (225, 155, 155),
        (246, 151, 132),
    },
    "lucy": {(191, 166, 144), (208, 190, 156)},
    "nancy": {(108, 110, 133), (216, 208, 224), (51, 131, 214), (42, 165, 226)},
}

# Colours shared by clothing and trousers.  Above the hem they are the shirt
# (ash's placket); below it the leg split takes over, so no height rule is
# needed -- but they are kept out of the hem search, which only trusts colours
# that are the shirt and nothing else.
TOP_SPATIAL: dict[str, set[tuple[int, int, int]]] = {
    "ash": {(128, 145, 165), (157, 163, 183), (139, 139, 171)},
}

# ---------------------------------------------------------------------------
# SHOE colours per base sprite.  Below the hem the feet are the only thing
# painted with them: every one of these is also the character's shirt colour
# (or, for lucy, a skin shade), which is why they are only looked for in the
# leg region.
# ---------------------------------------------------------------------------
SHOES: dict[str, set[tuple[int, int, int]]] = {
    "adam": {(128, 94, 142)},
    "ash": {(90, 68, 74), (111, 73, 77)},
    "lucy": {(199, 140, 89), (179, 94, 63)},
    "nancy": {(108, 110, 133), (216, 208, 224)},
}

# TROUSER colours per base sprite.  The hem is drawn at the shirt, but a walk
# frame can show a sliver of leg beside it, so a colour that is trousers and
# nothing else counts as trousers above the hem too -- unless it is one of the
# shared outline shades (nancy's), which would then repaint half the outline;
# hers are left to the silhouette.  The seated frames use the whole set.
PANTS: dict[str, set[tuple[int, int, int]]] = {
    "adam": {(104, 114, 83), (93, 96, 67)},
    "ash": {(120, 125, 147), (128, 145, 165)},
    "lucy": {(90, 103, 117), (106, 132, 147)},
    "nancy": {(86, 89, 114)},
}

# The four seated frames of the LimeZu layout (48-51).  They are not a pose of
# the walking character: the legs are bent forward, so the silhouette never
# narrows at the hem, and the front one is drawn with a pair of legs the four
# bases share.  They are split by colour instead, below the waist.
SIT_FRAMES = {48, 49, 50, 51}
SIT_MIN_Y = 36
SIT_SHOE_MIN_Y = 40
SIT_PANTS = {(199, 140, 89)}
SIT_SHOES = {(171, 74, 54)}

# ---------------------------------------------------------------------------
# Skin tones: (hue H 0-1, saturation S 0-1, vmin, vmax).
# "default" keeps the original colours (it is not remapped).
# ---------------------------------------------------------------------------
SKIN_TONES: dict[str, tuple[float, float, float, float] | None] = {
    "default": None,
    "light": (0.08, 0.20, 0.80, 1.00),
    "medium": (0.07, 0.40, 0.60, 0.88),
    "tan": (0.06, 0.50, 0.40, 0.72),
    "dark": (0.05, 0.55, 0.22, 0.52),
}

BASES = ["adam", "ash", "lucy", "nancy"]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def to_gray(rgb: tuple[int, int, int]) -> int:
    """Perceived luminance (rec. 601), preserves the pixel art's contrast."""
    r, g, b = rgb
    return min(255, round(0.299 * r + 0.587 * g + 0.114 * b))


def normalize(layer: Image.Image) -> None:
    """
    Stretches a greyscale layer so its brightest shade becomes white, in place.

    A tint multiplies the texel, so a layer that keeps the original luminance
    of, say, a dark olive shirt turns every colour you pick into a muddy
    version of itself -- pink hair came out maroon.  Scaling by a single factor
    keeps the shading intact and lets the chosen colour show at full strength.
    """
    px = layer.load()
    peak = 0
    for y in range(layer.height):
        for x in range(layer.width):
            r, _, _, a = px[x, y]
            if a:
                peak = max(peak, r)
    if peak == 0 or peak == 255:
        return
    for y in range(layer.height):
        for x in range(layer.width):
            r, _, _, a = px[x, y]
            if not a:
                continue
            v = min(255, round(r * 255 / peak))
            px[x, y] = (v, v, v, a)


def remap_skin(
    rgb: tuple[int, int, int], tone: tuple[float, float, float, float]
) -> tuple[int, int, int]:
    """Remaps a skin colour to a target tone (same method as person-avatars.py)."""
    _, _, v = colorsys.rgb_to_hsv(*(c / 255 for c in rgb))
    th, ts, vmin, vmax = tone
    nv = vmin + v * (vmax - vmin)
    r, g, b = colorsys.hsv_to_rgb(th, ts, nv)
    return (round(r * 255), round(g * 255), round(b * 255))


def frame_hem(base: str, src_px, fx: int) -> int:
    """
    The row where the legs start in this frame.

    It is the row right under the lowest pixel of the shirt, which follows the
    body as it bobs through the walk cycle -- a fixed row, or one guessed from
    how wide the silhouette is, both drift by an art pixel in the frames where
    one leg is lifted, and a drifting hem paints a stripe of shirt in the
    trouser colour.

    Only the shirt above `HEM_MAX` counts: every one of the four characters
    wears shoes in the same colour as its own shirt, and the shoes are always
    below that line.
    """
    lowest = 0
    for y in range(26, HEM_MAX, ART):
        for x in range(FRAME_W):
            r, g, b, a = src_px[fx + x, y]
            if a and (r, g, b) in TOP[base]:
                lowest = max(lowest, y)
                break
    if lowest == 0:
        return HEM_DEFAULT
    return min(max(lowest + ART, HEM_MIN), HEM_MAX)


def outer_contour(src_px, fx: int, hem: int) -> set[tuple[int, int]]:
    """
    Pixels of the leg region that draw the silhouette's outline.

    They stay in the body layer so the legs keep the same dark outline as the
    rest of the character whatever colour the trousers are tinted; everything
    they enclose is the part that gets recoloured.
    """
    contour: set[tuple[int, int]] = set()
    for y in range(hem, FRAME_H):
        for x in range(FRAME_W):
            if src_px[fx + x, y][3] == 0:
                continue
            for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                nx, ny = x + dx, y + dy
                if not (0 <= nx < FRAME_W and hem <= ny < FRAME_H):
                    contour.add((x, y))
                    break
                if src_px[fx + nx, ny][3] == 0:
                    contour.add((x, y))
                    break
    return contour


def classify_seated_leg(base: str, col: tuple[int, int, int], y_local: int) -> str:
    """
    Classifies a pixel below the waist of a seated frame.

    Trousers win over shoes because the pair of legs the front seated frame
    shares between the four bases is painted in the same tan lucy's shoes use,
    and the feet are only looked for near the floor: sitting sideways the torso
    reaches well below the waist, and every shoe colour is also a shirt colour.
    Anything else stays in the body.
    """
    if col in PANTS[base] or col in SIT_PANTS:
        return "pants"
    if y_local >= SIT_SHOE_MIN_Y and (col in SHOES[base] or col in SIT_SHOES):
        return "shoes"
    return "body"


def classify_pixel(base: str, col: tuple[int, int, int], y_local: int) -> str:
    """Classifies an opaque pixel above the hem as 'hair', 'top', 'pants' or 'body'."""
    if y_local >= HEM_MIN and col in PANTS[base] and col not in PROTECTED:
        return "pants"
    if col in HAIR[base]:
        return "hair"
    if col in TOP[base] or col in TOP_SPATIAL.get(base, set()):
        return "top"
    return "body"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def split_base(base: str) -> None:
    src = Image.open(AVATARS_DIR / f"{base}.png").convert("RGBA")
    w, h = src.size

    parts = {name: Image.new("RGBA", (w, h), (0, 0, 0, 0)) for name in ("hair", "top", "pants", "shoes")}
    body = Image.new("RGBA", (w, h), (0, 0, 0, 0))

    src_px = src.load()
    body_px = body.load()
    part_px = {name: im.load() for name, im in parts.items()}

    for frame in range(w // FRAME_W):
        fx = frame * FRAME_W
        seated = frame in SIT_FRAMES
        hem = SIT_MIN_Y if seated else frame_hem(base, src_px, fx)
        contour = set() if seated else outer_contour(src_px, fx, hem)
        for y in range(h):
            for x in range(FRAME_W):
                r, g, b, a = src_px[fx + x, y]
                if a == 0:
                    continue
                col = (r, g, b)
                if y >= hem and seated:
                    kind = classify_seated_leg(base, col, y)
                elif y >= hem:
                    # Below the hem everything the outline encloses is leg:
                    # the feet by their colour, the rest is trousers.
                    if col in SHOES[base]:
                        kind = "shoes"
                    elif (x, y) in contour or col in SKIN_COLORS or col in BARE_SKIN:
                        kind = "body"
                    else:
                        kind = "pants"
                else:
                    kind = classify_pixel(base, col, y)
                if kind == "body":
                    body_px[fx + x, y] = (r, g, b, a)
                else:
                    gray = to_gray(col)
                    part_px[kind][fx + x, y] = (gray, gray, gray, a)

    out = LAYERS_DIR / base
    out.mkdir(parents=True, exist_ok=True)
    for name, im in parts.items():
        normalize(im)
        file = "hair-short" if name == "hair" else name
        im.save(out / f"{file}.png", optimize=True)
        print(f"  {base}/{file}.png  (greyscale)")

    # Skin-tone variants of the body.
    for tone_name, tone in SKIN_TONES.items():
        body_var = body.copy()
        if tone is not None:
            bv = body_var.load()
            for y in range(h):
                for x in range(w):
                    r2, g2, b2, a2 = bv[x, y]
                    if a2 == 0:
                        continue
                    col2 = (r2, g2, b2)
                    if col2 in SKIN_COLORS:
                        bv[x, y] = (*remap_skin(col2, tone), a2)
        body_var.save(out / f"body-{tone_name}.png", optimize=True)
        print(f"  {base}/body-{tone_name}.png")


def main() -> None:
    print(f"Generating layers in {LAYERS_DIR}/\n")
    for base in BASES:
        print(f"[{base}]")
        split_base(base)
        print()
    print("Done.")


if __name__ == "__main__":
    main()
