#!/usr/bin/env python3
"""
Splits each base avatar (adam, ash, lucy, nancy) into three aligned layers
-- body, hair, top -- and generates the skin-tone variants for the body layer.
The hair and top layers are saved in greyscale so they can be tinted at runtime
with Phaser's `setTint()`.

Development only: the result is committed in
apps/client/public/assets/avatars/layers/.  Requires Python 3 and Pillow.

Usage:  python3 tools/split-layers.py

Layout of each layer: 1664x48 px (52 frames of 32x48), the same LimeZu layout as
the full avatars.  The pixels that do not belong to the layer are left
transparent (alpha 0).

Layers:
  body  -- skin, outlines, trousers, shoes, mouth; EVERYTHING but hair and top.
  hair  -- hair only, in greyscale (original brightness preserved).
  top   -- torso clothing only, in greyscale.

The skin variants are generated by remapping the skin colours (a subset of
PROTECTED) with an HSV rotation, in the style of person-avatars.py.  The
outlines, mouth, trousers and shoes do not change.

LimeZu's licence allows editing the assets (see docs/asset-licenses.md).
"""
from __future__ import annotations

import colorsys
from pathlib import Path

from PIL import Image

AVATARS_DIR = Path(__file__).resolve().parents[1] / "apps/client/public/assets/avatars"
LAYERS_DIR = AVATARS_DIR / "layers"

FRAME_H = 48  # height of one frame of the sprite sheet

# ---------------------------------------------------------------------------
# Colours shared by the 4 base characters.  They are the PROTECTED set of
# recolor-avatars.py: skin, mouth, outlines and shadows.
# ---------------------------------------------------------------------------
PROTECTED = {
    (58, 58, 80),
    (70, 70, 94),
    (86, 89, 114),
    (108, 89, 129),
    (120, 125, 147),
    (171, 74, 54),
    (199, 140, 89),
    (211, 163, 141),
    (246, 174, 159),
    (255, 203, 176),
}

# The subset of PROTECTED that is skin (remapped for the skin tones).
SKIN_COLORS = {
    (199, 140, 89),
    (211, 163, 141),
    (246, 174, 159),
    (255, 203, 176),
}

# Colours that are outlines/shadows/mouth and do NOT change with the skin tone.
FIXED_COLORS = PROTECTED - SKIN_COLORS

# ---------------------------------------------------------------------------
# HAIR colours per base sprite (from person-avatars.py + adam, analysed).
# ---------------------------------------------------------------------------
HAIR: dict[str, set[tuple[int, int, int]]] = {
    "adam": {(128, 94, 142), (159, 116, 168)},
    "ash": {(141, 112, 81), (138, 101, 82), (149, 115, 80), (186, 141, 94), (111, 84, 70)},
    "lucy": {(171, 103, 54), (179, 123, 63), (204, 150, 89), (175, 114, 59), (194, 136, 75), (179, 94, 63)},
    "nancy": {(114, 74, 64), (128, 84, 73), (131, 91, 76), (134, 97, 80), (123, 81, 71), (100, 73, 66)},
}

# ---------------------------------------------------------------------------
# CLOTHING colours (torso) per base sprite.
# ---------------------------------------------------------------------------
TOP: dict[str, set[tuple[int, int, int]]] = {
    "adam": {(104, 114, 83), (93, 96, 67), (95, 105, 74), (149, 157, 88)},
    "ash": {(90, 68, 74), (111, 73, 77), (162, 57, 75), (174, 74, 82), (225, 155, 155), (246, 151, 132)},
    "lucy": {(191, 166, 144), (208, 190, 156)},
    "nancy": {(108, 110, 133), (216, 208, 224), (51, 131, 214), (42, 165, 226)},
}

# Colours shared by clothing and trousers: they count as TOP only in the torso
# area (local y < 32).
TOP_SPATIAL: dict[str, set[tuple[int, int, int]]] = {
    "ash": {(128, 145, 165), (157, 163, 183), (139, 139, 171)},
}

# ---------------------------------------------------------------------------
# Skin tones: (hue H 0-1, saturation S 0-1, vmin, vmax).
# "default" keeps the original colours (it is not remapped).
# ---------------------------------------------------------------------------
SKIN_TONES: dict[str, tuple[float, float, float, float] | None] = {
    "default": None,
    "light": (0.08, 0.20, 0.80, 1.00),
    "medium": (0.07, 0.40, 0.60, 0.88),
    "tan": (0.06, 0.50, 0.40, 0.72),
    "dark": (0.05, 0.55, 0.22, 0.52),
}

BASES = ["adam", "ash", "lucy", "nancy"]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def to_gray(rgb: tuple[int, int, int]) -> int:
    """Perceived luminance (rec. 601), preserves the pixel art's contrast."""
    r, g, b = rgb
    return min(255, round(0.299 * r + 0.587 * g + 0.114 * b))


def remap_skin(rgb: tuple[int, int, int], tone: tuple[float, float, float, float]) -> tuple[int, int, int]:
    """Remaps a skin colour to a target tone (same method as person-avatars.py)."""
    _, _, v = colorsys.rgb_to_hsv(*(c / 255 for c in rgb))
    th, ts, vmin, vmax = tone
    nv = vmin + v * (vmax - vmin)
    r, g, b = colorsys.hsv_to_rgb(th, ts, nv)
    return (round(r * 255), round(g * 255), round(b * 255))


def classify_pixel(
    base: str, col: tuple[int, int, int], y_local: int,
) -> str:
    """Classifies an opaque pixel as 'hair', 'top' or 'body'."""
    if col in HAIR[base]:
        return "hair"
    if col in TOP[base]:
        return "top"
    spatial = TOP_SPATIAL.get(base, set())
    if col in spatial and y_local < 32:
        return "top"
    return "body"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def split_base(base: str) -> None:
    src = Image.open(AVATARS_DIR / f"{base}.png").convert("RGBA")
    w, h = src.size

    body = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    hair = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    top = Image.new("RGBA", (w, h), (0, 0, 0, 0))

    src_px = src.load()
    body_px = body.load()
    hair_px = hair.load()
    top_px = top.load()

    for y in range(h):
        y_local = y % FRAME_H
        for x in range(w):
            r, g, b, a = src_px[x, y]
            if a == 0:
                continue
            col = (r, g, b)
            kind = classify_pixel(base, col, y_local)
            if kind == "hair":
                gray = to_gray(col)
                hair_px[x, y] = (gray, gray, gray, a)
            elif kind == "top":
                gray = to_gray(col)
                top_px[x, y] = (gray, gray, gray, a)
            else:
                body_px[x, y] = (r, g, b, a)

    out = LAYERS_DIR / base
    out.mkdir(parents=True, exist_ok=True)
    hair.save(out / "hair.png", optimize=True)
    top.save(out / "top.png", optimize=True)
    print(f"  {base}/hair.png  (greyscale)")
    print(f"  {base}/top.png   (greyscale)")

    # Skin-tone variants of the body.
    for tone_name, tone in SKIN_TONES.items():
        body_var = body.copy()
        if tone is not None:
            bv = body_var.load()
            for y in range(h):
                for x in range(w):
                    r2, g2, b2, a2 = bv[x, y]
                    if a2 == 0:
                        continue
                    col2 = (r2, g2, b2)
                    if col2 in SKIN_COLORS:
                        bv[x, y] = (*remap_skin(col2, tone), a2)
        body_var.save(out / f"body-{tone_name}.png", optimize=True)
        print(f"  {base}/body-{tone_name}.png")


def main() -> None:
    print(f"Generando capas en {LAYERS_DIR}/\n")
    for base in BASES:
        print(f"[{base}]")
        split_base(base)
        print()
    print("Listo.")


if __name__ == "__main__":
    main()
